name: qsann
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - pip:
      - contourpy==1.3.2
      - cudensitymat-cu12==0.3.2
      - cupauliprop-cu12==0.1.0
      - cuquantum-cu12==25.11.0
      - custabilizer-cu12==0.1.0
      - custatevec-cu12==1.11.0
      - cutensor-cu12==2.4.1
      - cutensornet-cu12==2.10.0
      - cycler==0.12.1
      - dill==0.4.0
      - filelock==3.19.1
      - fire==0.7.1
      - fonttools==4.61.1
      - fsspec==2025.9.0
      - h5py==3.15.1
      - ImageIO==2.37.2
      - Jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy_loader==0.4
      - llvmlite==0.46.0
      - MarkupSafe==2.1.5
      - matplotlib==3.10.8
      - medmnist==3.0.2
      - mpmath==1.3.0
      - networkx==3.3
      - numba==0.63.1
      - numpy==1.26.4
      - pandas==2.3.3
      - pillow==11.3.0
      - ply==3.11
      - pynndescent==0.5.13
      - pyparsing==3.3.1
      - pytz==2025.2
      - qiskit==2.2.3
      - qiskit-aer==0.14.2
      - qiskit-aer-gpu==0.14.2
      - qiskit-terra==0.45.3
      - rustworkx==0.17.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - stevedore==5.6.0
      - symengine==0.14.1
      - sympy==1.14.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.3.1+cu121
      - torchaudio==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - tqdm==4.67.1
      - triton==2.3.1
      - tzdata==2025.2
      - umap-learn==0.5.9.post2